GAP/Controllers/ArticuloController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using GAP.Models;
using System.Collections;
using Comunes.Models;

namespace GAP.Controllers
{
    public class ArticuloController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public IEnumerable _ArticulosConMenorStock()
        {
            var articuloModels = db.ArticuloModels.Include(d => d.DepositoModels).
                OrderBy(x => (x.TotalEnBodega + x.TotalEnEstante)).Take(5);

            return articuloModels;
            //return View(articuloModels.ToList());
        }

        public IEnumerable _ArticulosConMayorStock()
        {
            var articuloModels = db.ArticuloModels.Include(d => d.DepositoModels).
                OrderByDescending(x => (x.TotalEnBodega + x.TotalEnEstante)).Take(5);

            return articuloModels;
            //return View(articuloModels.ToList());
        }

        // GET: Articulo
        public ActionResult Index()
        {
            var articuloModels = db.ArticuloModels.Include(a => a.DepositoModels);
            return View(articuloModels.ToList());
        }

        // GET: Articulo/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticuloModels articuloModels = db.ArticuloModels.Find(id);
            if (articuloModels == null)
            {
                return HttpNotFound();
            }
            return View(articuloModels);
        }

        // GET: Articulo/Create
        public ActionResult Create()
        {
            ViewBag.DepositoId = new SelectList(db.DepositoModels, "DepositoId", "Nombre");
            return View();
        }

        // POST: Articulo/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ArticuloId,Nombre,Descripcion,Precio,TotalEnEstante,TotalEnBodega,DepositoId")] ArticuloModels articuloModels)
        {
            if (ModelState.IsValid)
            {
                articuloModels.ArticuloId = Guid.NewGuid();
                db.ArticuloModels.Add(articuloModels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DepositoId = new SelectList(db.DepositoModels, "DepositoId", "Nombre", articuloModels.DepositoId);
            return View(articuloModels);
        }

        // GET: Articulo/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticuloModels articuloModels = db.ArticuloModels.Find(id);
            if (articuloModels == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepositoId = new SelectList(db.DepositoModels, "DepositoId", "Nombre", articuloModels.DepositoId);
            return View(articuloModels);
        }

        // POST: Articulo/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ArticuloId,Nombre,Descripcion,Precio,TotalEnEstante,TotalEnBodega,DepositoId")] ArticuloModels articuloModels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(articuloModels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DepositoId = new SelectList(db.DepositoModels, "DepositoId", "Nombre", articuloModels.DepositoId);
            return View(articuloModels);
        }

        // GET: Articulo/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticuloModels articuloModels = db.ArticuloModels.Find(id);
            if (articuloModels == null)
            {
                return HttpNotFound();
            }
            return View(articuloModels);
        }

        // POST: Articulo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            ArticuloModels articuloModels = db.ArticuloModels.Find(id);
            db.ArticuloModels.Remove(articuloModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GAP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GAP.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GAP/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GAP/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GAP/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <img class="slideFotos" id="inicio" src="~/Recursos/Deposito.jpg" />
    </div>
    <div class="col-md-12">
        <img class="slideFotos" src="~/Recursos/Articulos.jpg" />
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Artículos con menor stock</h2>
        @{ Html.RenderPartial("~/Views/Articulo/_ArticulosConMenorStock.cshtml", new GAP.Controllers.ArticuloController()._ArticulosConMenorStock()); }
        <p>@Html.ActionLink("Ver todos", "Index", "Articulo")</p>
    </div>
    <div class="col-md-6">
        <h2>Artículos con mayor stock</h2>
        @{ Html.RenderPartial("~/Views/Articulo/_ArticulosConMenorStock.cshtml", new GAP.Controllers.ArticuloController()._ArticulosConMayorStock()); }
        <p>@Html.ActionLink("Ver todos", "Index", "Articulo")</p>
    </div>
</div>